export const DatabaseTables = {
   userPrivate: "users-private",
    payment: "payments",
    textType: "text-types",
    industry: "industries",
    order: "orders",
    document: "docs",
    writerFeedback: "writer-feedback",
    clientFeedback: "client-feedback",
    notifications: "notifications",
    buyerInvoices: "buyer-invoices",
    publishIncoices: "publish-invoices",
    writerInvoices: "writer-invoices",

    userPublic: "users",
    writerPayout: "writer-invoice",
    companyPayout: "company-invoice",
    lead: "lead",
    notification: "notifications",
    publisherPublic: "publishers",
    publisherPrivate: "publishers-private",
    publishTask: "publish-tasks",
    publishPRTask: "publish-public-release-tasks",
    publishOrder: "publish-orders",
    publishOrderHistory: "publish-orders-history",
    portalPublic: "portals",
    portalPrivate: "portals-private",
    publishPublicRelease: "publish-public-releases",
    publicRelease: "public-releases",
    atomicOperations: "atomic-operations",
    publicPressReleasePublishLog: "public-press-release-publish-log",
    seoDoc: "documents",
    anonOrder: "anon-order",
    agency: "seo-agencies",
    agencyPrivate: "seo-agencies-private",
    aiUsageLogs: "AI-usage-logs",
}
